#!/bin/bash

if [ ! -z "`which php`" ]; then
    ttest=`echo "<?php echo \\\$argv[1] ?>" | php -- "blabla"`
    if [ "$ttest" = "blabla" ]; then
        out=`php "${TEST_ENV_DIR}/modules/parser/non-bash/aria2/php/parselogs.php" "$PARSER_NAME" "$1" "$2"`
        ( echo $out >&2 ) > /dev/null
        if [ "$out" != "" ]; then
            logError "$out"
            fail
        fi
        return 0
    fi
fi

return 1
