#!/bin/bash

#
# A skeleton implementation (i.e. interface description) of the builder API.
# The interface described in this file should be implemented by every builder module.
# Module implementors can copy this file and modify it as they see fit.
# Minimal implementations need only implement builderBuildCommand
#

##
# Outputs the command line for building a client.
# Note: should not attempt to do the building itself!
#
# @output   The command line for building a client.
##
function builderBuildCommand() {
    # TODO
    echo "TO BE IMPLEMENTED"
}

##
# Builds the client on the local machine.
#
# @param    Directory where the client's sources reside.
#
# @return   True (0) iff the build command seems to have succeeded succesfully.
##
function builderBuildLocal() {
    # The default implementation changes directory and calls the build command, encapsulating it in a bit of bash scripting to check whether it succeeds.
    if builderBuildLocal__default "$1"; then
        return 0
    fi
    return 1
}

##
# Builds the client on the remote machine.
# Use the Host API to send commands.
#
# @param    Remote directory where the client's sources reside.
#
# @return   True (0) iff the build command seems to have succeeded succesfully.
##
function builderBuildRemote() {
    # The default implementation changes directory and calls the build command, encapsulating it in a bit of bash scripting to check whether it succeeds.
    if builderBuildRemote__default "$1"; then
        return 0
    fi
    return 1
}

##
# This function returns the API version implemented in this module.
# You should always leave this number in tact, unless you have upgraded the module to another version.
# This version number is used to check compatibilities with the core.
#
# @output   The API version number.
##
function builderAPIVersion() {
    echo "1.0.4"
}
