#!/bin/bash

#
# A straighforward implementation of the source API, mimicking the way CLIENT_LOCATION is interpreted when not building.
#
# This module interprets CLIENT_LOCATION as follows:
# The already existing directory in which the source resides. NO new directories are created and builds are made in the existing directories (and most likely not cleaned).
#
# This is the default source module.
#

##
# Outputs the command line for retrieving the source code of a client.
# Interpret $CLIENT_LOCATION for figuring out where the source is to be fetched from.
# Note: should not attempt to do the retrieving itself!
#
# @output   The command line for retrieving the source code of a client.
##
function sourcePrepareCommand() {
    echo ""
    # No command is needed to fetch the source if it's assumed to be there already.
}

##
# Prepares the source code of the client on the local machine.
#
# @return   True (0) iff the prepare command seems to have succeeded succesfully.
##
function sourcePrepareLocal() {
    # Only check that the source location exists; other than that it should already be prepared
    if [ ! -d "$CLIENT_LOCATION" ]; then
        logError "source:directory :: The source directory \"$CLIENT_LOCATION\" of client $CLIENT_NAME seems not to exist."
        return 1
    fi
    return 0
}

##
# Prepares the source code of the client on the remote machine.
# Use the Host API to send commands.
#
# @return   True (0) iff the prepare command seems to have succeeded succesfully.
##
function sourcePrepareRemote() {
    # Only check that the source location exists remotely; other than that it should already be prepared
    ans=`hostSendCommand "cd; [ -d \"$CLIENT_LOCATION\" ] && echo -n \"OK\""`
    if [ "$ans" != "OK" ]; then
        logError "source:directory :: The source directory \"$CLIENT_LOCATION\" of client $CLIENT_NAME seems not to exist on host $HOST_NAME."
        return 1
    fi
    return 0
}

##
# Outputs the local directory in which the source was prepared.
# Note that this is a static function that does not track whether the directory was actually created: use this directory only after calling sourcePrepareLocal.
#
# @output   The local directory in which the sources reside.
##
function sourceLocalLocation() {
    echo "$CLIENT_LOCATION"
}

##
# Outputs the remote directory in which the source was prepared.
# Note that this is a static function that does not track whether the directory was actually created: use this directory only after calling sourcePrepareRemote.
#
# @output   The remote directory in which the sources reside.
##
function sourceRemoteLocation() {
    echo "$CLIENT_LOCATION"
}

##
# This function returns the API version implemented in this module.
# You should always leave this number in tact, unless you have upgraded the module to another version.
# This version number is used to check compatibilities with the core.
#
# @output   The API version number.
##
function sourceAPIVersion() {
    echo "1.0.0"
}
