#!/bin/bash

#
# A skeleton implementation (i.e. interface description) for the viewer API.
# The interface described in this file should be implemented by each viewer module.
# Module implementors can copy this file and modify it as they see fit.
# Minimal implementation that have no further parameters than the generic parameters need only implement viewerCreateView. Do not forget to update the module name in viewerLoadSettings!
#
# This module expects to find the following processed files:
# - FILL IN
# - FILL IN
# - FILL IN
# ...
#

##
# Read settings from the provided settings file and save them to ${LOCAL_TEST_DIR}/viewers/view_$VIEWER_NUMBER .
# Please return false (non-0) when an error occurs, instead of calling fail.
# The way the settings are saved into ${LOCAL_TEST_DIR}/viewers/view_$VIEWER_NUMBER/ does not matter, but make sure it exists and that ${LOCAL_TEST_DIR}/viewers/view_$VIEWER_NUMBER/modulename contains the module subtype and nothing else.
#
# @param    The settings file to read from.
# @param    The line number at which this viewer object was defined. The first line in the settings file is at line $(($2 + 1))
#
# @return   True (0) iff the settings were parsed and saves succesfully.
##
function viewerReadSettings() {
    local parameterName=""
    local parameterValue=""
    LINE_NUMBER=$(($2 + 1))
    # Parse all parameters
    while IFS="" read LINE; do
        if [ "" = "$LINE" ]; then
            LINE_NUMBER=$(($LINE_NUMBER + 1))
            continue
        fi

        parameterName=`getParameterName "$LINE"`
        checkFailScenarioFile "$6"
        parameterValue=`getParameterValue "$LINE"`
        # Handle this parameter appropiately
        case $parameterName in
            *)
                logError "viewer:_skeleton_ :: Unknown parameter name \"$parameterName\" in viewer $VIEWER_NUMBER. Ignoring."
                ;;
        esac
        LINE_NUMBER=$(($LINE_NUMBER + 1))
    done < "$1";

    # Delegate the rest to the default implementation
    viewerReadSettings__default
    # Any variables set up above should be saved like this:
    # echo "YOUR_SETTING=\"$YOUR_SETTING\"" >> "${LOCAL_TEST_DIR}/viewers/view_$VIEWER_NUMBER/conf"

    return 0
}

##
# Loads previously saved settings into memory.
# Be sure to override all relevant variables, whether they're saved or not.
#
# @param    The name of the file object to be loaded.
##
function viewerLoadSettings() {
    # By default delegated to the default implementation, which works fine if the default implementation for viewerReadSettings is used
    # TODO: CHANGE MODULE NAME BELOW
    viewerLoadSettings__default "$1" "MODULE_SUBTYPE"
}

##
# Creates the view from the processed data.
#
# @param    processedDir    The directory on the local machine where processed data resides.
# @param    viewDir         The directory on the local machine where views are to be placed.
##
function viewerCreateView() {
    #TODO
    echo "TO BE IMPLEMENTED"
}

##
# This function returns the API version implemented in this object.
# You should always leave this number in tact, unless you have upgraded the module to another version.
# This version number is used to check compatibilities with the core.
#
# @output   The API version number.
##
function viewerAPIVersion() {
    echo "1.0.4"
}
