#!/bin/bash

HOST_NAME="localhost"
HOST_TC_IFACE="eth0"

HOST_TC_INBOUNDPORTS=""
HOST_TC_OUTBOUNDPORTS=""
HOST_TC_LOSS="0.0"
HOST_TC_CORRUPTION="0.0"
HOST_TC_DUPLICATION="0.0"
HOST_TC_DOWN=""
HOST_TC_DOWN_BURST=""
HOST_TC_UP=""
HOST_TC_UP_BURST=""
HOST_TC_DELAY="0ms"

function logError() { echo "$1"; }; function hostSendCommand() { bash -l -c "cd; $1"; }; function fail() { echo "FAIL"; echo "FAIL"; exit; }
. netem

tcCheck || fail

tcInstall "192.168.0.1"
